# Generated by Django 5.0 on 2023-12-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisy', '0004_alter_promo_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo',
            field=models.TextField(default='kisypromo3633575', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
