# Generated by Django 5.0 on 2023-12-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisy', '0007_alter_promo_promo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo',
            field=models.TextField(default='kisypromo5198790', max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'email', 'phone')},
        ),
    ]
