# Generated by Django 5.0 on 2023-12-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisy', '0018_alter_promo_promo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'phone')},
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo',
            field=models.TextField(default='kisypromo1894722', max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
