# Generated by Django 5.0 on 2023-12-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisy', '0019_alter_user_unique_together_alter_promo_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
