# Generated by Django 5.0 on 2023-12-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisy', '0021_alter_promo_discount_alter_promo_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
