# Generated by Django 5.0 on 2023-12-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kisy', '0024_rename_email_user_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'phone')},
        ),
    ]
