# Generated by Django 5.0 on 2023-12-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kisy', '0025_rename_username_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
