# Generated by Django 5.0 on 2023-12-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisy', '0026_remove_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
